


export const Products = [
    {
      id: 1,
      productName: 'Smartphone XYZ',
      Price: 10000,
      productImage: '/Assets/product3.jpeg',
      productDescription: 'Experience the latest in mobile ',
      category: 'Electronics',
    },
    {
      id: 2,
      productName: 'Advanced Tractor 2000',
      Price: 160000,
      productImage: '/Assets/tractor.png',
      productDescription: 'Boost your farming efficiency with ',
      category: 'Farm Equipment',
    },
    {
      id: 3,
      productName: 'Heavy-duty Crane',
      Price: 120999,
      productImage: '/Assets/crane.jpeg',
      productDescription: 'Handle heavy lifting with ease.',
      category: 'Construction',
    },
    {
      id: 4,
      productName: 'Premium XYZ Product',
      Price: 6000,
      productImage: '/Assets/product3.jpeg',
      productDescription: 'Discover excellence with our . ',
      category: 'General',
    },
    {
      id: 5,
      productName: 'Innovative ABC Gadget',
      Price: 6000,
      productImage: '/Assets/tractor.png',
      productDescription: 'Stay ahead with our ',
      category: 'Gadgets',
    },
    {
      id: 6,
      productName: 'Sweet Watermelon',
      Price: 6000,
      productImage: '/Assets/product4.jpeg',
      productDescription: 'Enjoy the sweetness .',
      category: 'Fruits',
    },
    {
      id: 7,
      productName: 'Eco-friendly XYZ Product',
      Price: 6000,
      productImage: '/Assets/product3.jpeg',
      productDescription: 'Embrace sustainability ',
      category: 'Sustainable Living',
    },
    {
      id: 8,
      productName: 'Smartphone XYZ',
      Price: 10000,
      productImage: '/Assets/product3.jpeg',
      productDescription: 'Experience the latest in mobile ',
      category: 'Electronics',
    },
    {
      id: 9,
      productName: 'Advanced Tractor 2000',
      Price: 160000,
      productImage: '/Assets/tractor.png',
      productDescription: 'Boost your farming efficiency with ',
      category: 'Farm Equipment',
    },
    {
      id: 10,
      productName: 'Heavy-duty Crane',
      Price: 120999,
      productImage: '/Assets/crane.jpeg',
      productDescription: 'Handle heavy lifting with ease.',
      category: 'Construction',
    },
    {
      id: 11,
      productName: 'Premium XYZ Product',
      Price: 6000,
      productImage: '/Assets/product3.jpeg',
      productDescription: 'Discover excellence with our . ',
      category: 'General',
    },
    {
      id: 12,
      productName: 'Innovative ABC Gadget',
      Price: 6000,
      productImage: '/Assets/tractor.png',
      productDescription: 'Stay ahead with our ',
      category: 'Gadgets',
    },
    {
      id: 13,
      productName: 'Sweet Watermelon',
      Price: 6000,
      productImage: '/Assets/product4.jpeg',
      productDescription: 'Enjoy the sweetness .',
      category: 'Fruits',
    },
    {
      id: 14,
      productName: 'Eco-friendly XYZ Product',
      Price: 6000,
      productImage: '/Assets/product3.jpeg',
      productDescription: 'Embrace sustainability ',
      category: 'Sustainable Living',
    },
  ];
  